backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    preview_path: blog/{{slug}}
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Featured Image, name: "thumbnail", widget: "image"}
      - {label: Body, name: body, widget: markdown}
      - {label: "Category", name: "category", widget: "relation", collection: 'categories', searchField: ["title"], displayField: ["title"], valueField: "title", multiple: true}
      - {label: "Category", name: "category", widget: "select", option: ["one", "two"] }
  - name: categories
    label: Categories
    folder: "source/categories"
    format: frontmatter
    identifier_field: title
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields: 
      - {label: "Category Title", name: "title", widget: "string"}